export interface TheoryDimension {
  position: string;
  evidence: string[];
  citations: string[];
  explanation: string;
}

export interface Theory {
  id: string;
  name: string;
  researchers: string[];
  year: number;
  color: string;
  shortDescription: string;
  fullDescription: string;
  dimensions: Record<string, TheoryDimension>;
  testablePredictions: string[];
  majorCriticisms: string[];
  scientificInfluence: "Very High" | "High" | "Moderate" | "Growing" | "Niche";
  relatedConcepts: string[];
  relatedDebates: string[];
  keyBooks: string[];
}

export const THEORY_DIMENSIONS = [
  "definition",
  "qualia",
  "hardProblem",
  "self",
  "freeWill",
  "bodyRole",
  "emotionRole",
  "neuralBasis",
  "animalConsciousness",
  "aiConsciousness",
  "evidence",
  "criticisms",
  "predictions",
  "influence",
];

export const THEORIES: Record<string, Theory> = {
  iit: {
    id: "iit",
    name: "Integrated Information Theory",
    researchers: ["Giulio Tononi", "Christof Koch"],
    year: 2004,
    color: "from-purple-500 to-pink-600",
    shortDescription: "Consciousness is integrated information (Φ) in a system",
    fullDescription:
      "IIT proposes that consciousness corresponds to integrated information in a physical system. The more integrated information a system generates, the more conscious it is. Consciousness is a fundamental property of matter, not limited to brains.",
    dimensions: {
      definition: {
        position: "Consciousness = integrated information (Φ) in a system",
        evidence: ["Phi correlates with consciousness levels", "Explains unity of consciousness"],
        citations: ["Tononi 2004", "Koch & Tononi 2015"],
        explanation:
          "Consciousness is quantified by phi (Φ), a measure of integrated information. A system is conscious to the degree it integrates information irreducibly. This provides a mathematical framework for consciousness.",
      },
      qualia: {
        position: "Qualia are intrinsic properties of integrated information",
        evidence: ["Explains why experiences feel the way they do", "Predicts quale structure"],
        citations: ["Tononi 2012"],
        explanation:
          "The specific quality of an experience (redness of red) corresponds to the specific pattern of integrated information. Different patterns generate different qualia.",
      },
      hardProblem: {
        position: "Hard problem is solved by identifying consciousness with Φ",
        evidence: ["Mathematical framework", "Explains why information integration feels like something"],
        citations: ["Tononi 2015"],
        explanation:
          "IIT claims the hard problem dissolves once we recognize consciousness as a fundamental property of integrated information, not something that needs to be derived from physical properties.",
      },
      self: {
        position: "Self emerges from integrated information in brain",
        evidence: ["Explains unity of self", "Predicts self-consciousness in integrated systems"],
        citations: ["Tononi & Koch 2015"],
        explanation:
          "The sense of self arises from the integrated information generated by the brain's core systems. Different levels of integration produce different levels of self-awareness.",
      },
      freeWill: {
        position: "Free will emerges from integrated information dynamics",
        evidence: ["Explains why choices feel free", "Predicts determinism and freedom coexist"],
        citations: ["Tononi 2012"],
        explanation:
          "Free will is compatible with determinism because the integrated information in a system generates genuine causal power. Choices are determined but still free because they arise from the system's integrated information.",
      },
      bodyRole: {
        position: "Body is part of the integrated system but not essential",
        evidence: ["Brain alone can be conscious", "Explains why brain damage affects consciousness"],
        citations: ["Tononi 2004"],
        explanation:
          "While the body provides input to the brain, consciousness primarily depends on integrated information in the brain. The body's role is informational, not constitutive.",
      },
      emotionRole: {
        position: "Emotion is one type of integrated information",
        evidence: ["Explains emotional consciousness", "Predicts emotion in any integrated system"],
        citations: ["Tononi 2012"],
        explanation:
          "Emotions are patterns of integrated information, not special. Any system with appropriate integration can have emotional experiences.",
      },
      neuralBasis: {
        position: "Thalamocortical system is the main neural basis of consciousness",
        evidence: ["Phi highest in thalamocortical loops", "Explains anesthesia effects"],
        citations: ["Tononi & Koch 2015", "Mashour et al. 2020"],
        explanation:
          "The thalamocortical system generates the most integrated information in the brain. Consciousness correlates with phi in this system. Anesthetics reduce phi, explaining loss of consciousness.",
      },
      animalConsciousness: {
        position: "Any system with integrated information is conscious",
        evidence: ["Predicts consciousness in many animals", "Explains varying levels of consciousness"],
        citations: ["Tononi 2012"],
        explanation:
          "Animals with integrated information systems are conscious. The degree of consciousness depends on the amount of integrated information. This predicts consciousness in birds, octopuses, and possibly insects.",
      },
      aiConsciousness: {
        position: "AI can be conscious if it generates integrated information",
        evidence: ["Phi can be measured in artificial systems", "Consciousness is substrate-independent"],
        citations: ["Tononi 2015"],
        explanation:
          "Consciousness is not biological. Any artificial system that generates integrated information would be conscious. Current AI systems likely have low phi and minimal consciousness.",
      },
      evidence: {
        position: "Phi correlates with consciousness levels across species and conditions",
        evidence: [
          "Phi decreases during anesthesia",
          "Phi increases during wakefulness",
          "Phi correlates with consciousness in disorders of consciousness",
          "Phi predicts consciousness in split-brain patients",
        ],
        citations: ["Tononi et al. 2016", "Mashour et al. 2020"],
        explanation:
          "Empirical evidence shows phi correlates with consciousness levels. Anesthesia reduces phi and consciousness. Wakefulness increases both. Patients in vegetative states have low phi.",
      },
      criticisms: {
        position: "IIT faces challenges with empirical testing and philosophical assumptions",
        evidence: [
          "Phi calculation is computationally intractable",
          "Predicts consciousness in simple systems (e.g., photodiodes)",
          "Doesn't explain why integration matters",
          "Difficult to test in complex systems",
        ],
        citations: ["Oizumi et al. 2014", "Dennett 2015"],
        explanation:
          "Critics argue IIT may attribute consciousness to systems that clearly aren't conscious. The theory is also difficult to test empirically because calculating phi is computationally intensive.",
      },
      predictions: {
        position: "IIT makes specific, testable predictions about consciousness",
        evidence: [
          "Predicts which brain regions matter for consciousness",
          "Predicts consciousness in split-brain patients",
          "Predicts effects of anesthetics",
          "Predicts consciousness in disorders of consciousness",
        ],
        citations: ["Tononi 2015"],
        explanation:
          "IIT generates testable predictions: consciousness should correlate with phi, anesthetics should reduce phi, brain lesions should reduce phi, and consciousness should be absent in systems with low phi.",
      },
      influence: {
        position: "Very High - IIT is one of the most influential theories of consciousness",
        evidence: ["Thousands of citations", "Drives research on neural correlates", "Influences neuroscience funding"],
        citations: ["Google Scholar", "NIH funding data"],
        explanation:
          "IIT has become one of the most influential consciousness theories. It drives research on neural correlates of consciousness and influences how neuroscientists think about consciousness.",
      },
    },
    testablePredictions: [
      "Phi should correlate with consciousness levels",
      "Anesthetics should reduce phi",
      "Brain lesions should reduce phi proportionally to consciousness loss",
      "Consciousness should be absent in systems with phi near zero",
      "Split-brain patients should have reduced phi",
    ],
    majorCriticisms: [
      "Phi calculation is computationally intractable",
      "May attribute consciousness to simple systems",
      "Doesn't explain why integration matters for consciousness",
      "Difficult to test in complex biological systems",
      "Assumes consciousness is a fundamental property without justification",
    ],
    scientificInfluence: "Very High",
    relatedConcepts: ["Consciousness", "Integration", "Information", "Neural Correlates"],
    relatedDebates: ["Hard Problem", "Unity of Consciousness", "Animal Consciousness"],
    keyBooks: ["phi", "search-consciousness"],
  },

  gwt: {
    id: "gwt",
    name: "Global Workspace Theory",
    researchers: ["Bernard Baars", "Stanislas Dehaene"],
    year: 1988,
    color: "from-blue-500 to-cyan-600",
    shortDescription: "Consciousness is information broadcast globally in the brain",
    fullDescription:
      "GWT proposes that consciousness arises when information enters a 'global workspace' in the brain, where it is broadcast to many cognitive processes. Only information in the workspace is conscious.",
    dimensions: {
      definition: {
        position: "Consciousness = information in global workspace",
        evidence: ["Explains limited conscious capacity", "Explains attention"],
        citations: ["Baars 1988", "Dehaene 2014"],
        explanation:
          "Consciousness is the global broadcasting of information. When information enters the global workspace, it becomes conscious. Only one stream of information can occupy the workspace at a time.",
      },
      qualia: {
        position: "Qualia are properties of globally broadcast information",
        evidence: ["Explains why some information is conscious", "Predicts quale properties"],
        citations: ["Baars 2005"],
        explanation:
          "The specific quality of an experience depends on which information is broadcast and how it's processed. Different broadcast patterns generate different qualia.",
      },
      hardProblem: {
        position: "Hard problem remains but is addressed by identifying conscious access",
        evidence: ["Explains access consciousness", "Doesn't fully explain phenomenal consciousness"],
        citations: ["Baars 1988"],
        explanation:
          "GWT explains why information becomes accessible to consciousness but doesn't fully explain why access feels like something. The hard problem remains partially unsolved.",
      },
      self: {
        position: "Self is a model in the global workspace",
        evidence: ["Explains self-awareness", "Predicts self-consciousness in broadcast systems"],
        citations: ["Baars 2007"],
        explanation:
          "The sense of self arises when self-related information enters the global workspace. Self-consciousness is the broadcast of self-models.",
      },
      freeWill: {
        position: "Free will emerges from global workspace dynamics",
        evidence: ["Explains why choices feel free", "Predicts determinism and freedom coexist"],
        citations: ["Baars 2005"],
        explanation:
          "Free will arises from the global workspace's ability to integrate information and make decisions. Choices are determined but feel free because they arise from conscious deliberation.",
      },
      bodyRole: {
        position: "Body provides input to workspace but is not essential",
        evidence: ["Brain alone can be conscious", "Body damage affects consciousness indirectly"],
        citations: ["Baars 1988"],
        explanation:
          "The body provides sensory input to the brain, which enters the global workspace. But consciousness depends on the workspace, not the body itself.",
      },
      emotionRole: {
        position: "Emotion is information that enters the global workspace",
        evidence: ["Explains emotional consciousness", "Predicts emotion in any system with workspace"],
        citations: ["Baars 2005"],
        explanation:
          "Emotions are patterns of information that can enter the global workspace. Emotional consciousness occurs when emotional information is broadcast.",
      },
      neuralBasis: {
        position: "Prefrontal cortex and anterior cingulate are key workspace regions",
        evidence: ["fMRI shows activation during consciousness", "Lesions impair consciousness"],
        citations: ["Dehaene & Changeux 2011"],
        explanation:
          "The global workspace is implemented in prefrontal and parietal cortex. These regions broadcast information to other brain areas. Damage here impairs consciousness.",
      },
      animalConsciousness: {
        position: "Animals with global workspaces are conscious",
        evidence: ["Predicts consciousness in many mammals", "Explains varying levels of consciousness"],
        citations: ["Baars 2005"],
        explanation:
          "Animals with brain structures that broadcast information globally are conscious. The degree of consciousness depends on workspace sophistication.",
      },
      aiConsciousness: {
        position: "AI can be conscious if it has a global workspace",
        evidence: ["Workspace is a computational architecture", "Consciousness is substrate-independent"],
        citations: ["Baars 2005"],
        explanation:
          "Consciousness is not biological. Any artificial system with a global workspace architecture would be conscious. Current AI systems lack this architecture.",
      },
      evidence: {
        position: "Global ignition events correlate with consciousness",
        evidence: [
          "fMRI shows global ignition during consciousness",
          "EEG shows global broadcasting during consciousness",
          "Anesthesia blocks global ignition",
          "Sleep reduces global broadcasting",
        ],
        citations: ["Dehaene et al. 2014", "Mashour et al. 2020"],
        explanation:
          "Empirical evidence shows that consciousness correlates with global broadcasting of information. When information is broadcast globally, it becomes conscious.",
      },
      criticisms: {
        position: "GWT faces challenges explaining phenomenal consciousness",
        evidence: [
          "Doesn't explain why broadcasting feels like something",
          "Doesn't explain qualia",
          "Difficult to distinguish from access consciousness",
          "May not explain all forms of consciousness",
        ],
        citations: ["Block 2005", "Dennett 2005"],
        explanation:
          "Critics argue GWT explains access consciousness but not phenomenal consciousness. It doesn't explain why global broadcasting generates subjective experience.",
      },
      predictions: {
        position: "GWT makes specific predictions about consciousness",
        evidence: [
          "Predicts global ignition during consciousness",
          "Predicts consciousness loss during anesthesia",
          "Predicts limited conscious capacity",
          "Predicts consciousness in systems with global broadcasting",
        ],
        citations: ["Dehaene 2014"],
        explanation:
          "GWT predicts consciousness should correlate with global broadcasting, anesthetics should block broadcasting, and consciousness should be limited by workspace capacity.",
      },
      influence: {
        position: "Very High - GWT is one of the most influential theories",
        evidence: ["Thousands of citations", "Drives research on neural correlates", "Widely taught in neuroscience"],
        citations: ["Google Scholar", "Neuroscience textbooks"],
        explanation:
          "GWT has been highly influential in consciousness research. It provides a clear framework for understanding consciousness and drives empirical research.",
      },
    },
    testablePredictions: [
      "Global ignition events should correlate with consciousness",
      "Anesthetics should block global broadcasting",
      "Consciousness should be limited by workspace capacity",
      "Brain lesions should impair global broadcasting",
      "Consciousness should require prefrontal-parietal activation",
    ],
    majorCriticisms: [
      "Doesn't explain phenomenal consciousness, only access consciousness",
      "Doesn't explain why broadcasting feels like something",
      "Difficult to distinguish from other theories",
      "May not explain all forms of consciousness",
      "Workspace metaphor may be oversimplified",
    ],
    scientificInfluence: "Very High",
    relatedConcepts: ["Consciousness", "Global Workspace", "Access Consciousness", "Attention"],
    relatedDebates: ["Hard Problem", "Access vs Phenomenal Consciousness"],
    keyBooks: ["consciousness-brain", "consciousness-explained"],
  },

  hot: {
    id: "hot",
    name: "Higher-Order Thought Theory",
    researchers: ["David Rosenthal", "Axel Cleeremans"],
    year: 1997,
    color: "from-yellow-500 to-orange-600",
    shortDescription: "Consciousness requires thoughts about thoughts",
    fullDescription:
      "HOT proposes that a mental state is conscious if and only if it is the object of a higher-order representation. Consciousness requires meta-representation: thinking about your thoughts.",
    dimensions: {
      definition: {
        position: "Consciousness = higher-order representation of mental states",
        evidence: ["Explains why some thoughts are conscious", "Explains self-awareness"],
        citations: ["Rosenthal 1997", "Cleeremans 2005"],
        explanation:
          "A mental state is conscious when you have a higher-order thought about it. Without the higher-order representation, the mental state is unconscious.",
      },
      qualia: {
        position: "Qualia are properties of higher-order thoughts",
        evidence: ["Explains quale properties", "Predicts qualia structure"],
        citations: ["Rosenthal 2005"],
        explanation:
          "The specific quality of an experience depends on the content of the higher-order thought. Different higher-order thoughts generate different qualia.",
      },
      hardProblem: {
        position: "Hard problem is addressed by meta-representation",
        evidence: ["Explains why thoughts feel like something", "Explains subjective experience"],
        citations: ["Rosenthal 2005"],
        explanation:
          "The hard problem is solved by recognizing that consciousness requires meta-representation. The subjective quality arises from higher-order thoughts about mental states.",
      },
      self: {
        position: "Self is a higher-order representation of the body and mind",
        evidence: ["Explains self-awareness", "Predicts self-consciousness in thinking creatures"],
        citations: ["Rosenthal 2005"],
        explanation:
          "Self-awareness is the higher-order representation of your own mental states and body. The sense of self arises from meta-representation.",
      },
      freeWill: {
        position: "Free will requires higher-order representation of choices",
        evidence: ["Explains why choices feel free", "Predicts freedom in thinking creatures"],
        citations: ["Rosenthal 2005"],
        explanation:
          "Free will arises when you have higher-order thoughts about your choices. Conscious deliberation involves meta-representation of decision-making.",
      },
      bodyRole: {
        position: "Body is represented in higher-order thoughts",
        evidence: ["Explains bodily awareness", "Predicts body consciousness"],
        citations: ["Rosenthal 2005"],
        explanation:
          "Body awareness is a higher-order representation of bodily states. The body itself is not essential; what matters is the representation.",
      },
      emotionRole: {
        position: "Emotion is a mental state that can be represented higher-order",
        evidence: ["Explains emotional consciousness", "Predicts emotion in thinking creatures"],
        citations: ["Rosenthal 2005"],
        explanation:
          "Emotional consciousness occurs when you have higher-order thoughts about emotional states. The emotion itself is unconscious until represented.",
      },
      neuralBasis: {
        position: "Prefrontal cortex generates higher-order representations",
        evidence: ["fMRI shows prefrontal activation during consciousness", "Lesions impair consciousness"],
        citations: ["Lau & Rosenthal 2011"],
        explanation:
          "The prefrontal cortex generates higher-order representations. Consciousness depends on prefrontal function. Damage here impairs consciousness.",
      },
      animalConsciousness: {
        position: "Only animals capable of meta-representation are conscious",
        evidence: ["Predicts consciousness in primates and some mammals", "Explains limited consciousness in other animals"],
        citations: ["Rosenthal 2005"],
        explanation:
          "Only animals capable of higher-order thought are conscious. This limits consciousness to primates and possibly some other mammals.",
      },
      aiConsciousness: {
        position: "AI can be conscious if it can represent its own thoughts",
        evidence: ["Meta-representation is computational", "Consciousness is substrate-independent"],
        citations: ["Rosenthal 2005"],
        explanation:
          "Consciousness is not biological. Any artificial system capable of meta-representation would be conscious. Current AI systems have limited meta-representation.",
      },
      evidence: {
        position: "Meta-representation correlates with consciousness",
        evidence: [
          "fMRI shows prefrontal activation during consciousness",
          "Meta-cognitive accuracy correlates with consciousness",
          "Anesthesia impairs meta-representation",
          "Sleep reduces meta-representation",
        ],
        citations: ["Lau & Rosenthal 2011"],
        explanation:
          "Empirical evidence shows consciousness correlates with meta-representation. When you can represent your own thoughts, you are conscious.",
      },
      criticisms: {
        position: "HOT faces challenges with infinite regress and empirical testing",
        evidence: [
          "Infinite regress problem: higher-order thoughts need higher-order thoughts",
          "Difficult to test empirically",
          "May not explain all forms of consciousness",
          "Predicts limited consciousness in animals",
        ],
        citations: ["Block 2005", "Dennett 2005"],
        explanation:
          "Critics argue HOT faces the infinite regress problem: if consciousness requires higher-order thoughts, don't those thoughts require even higher-order thoughts? Also difficult to test empirically.",
      },
      predictions: {
        position: "HOT makes specific predictions about consciousness",
        evidence: [
          "Predicts consciousness correlates with meta-representation",
          "Predicts limited consciousness in animals without meta-representation",
          "Predicts consciousness loss during anesthesia",
          "Predicts consciousness in systems with meta-representation",
        ],
        citations: ["Rosenthal 2005"],
        explanation:
          "HOT predicts consciousness should correlate with meta-representation, only creatures with higher-order thoughts should be conscious, and anesthetics should impair meta-representation.",
      },
      influence: {
        position: "High - HOT is an influential theory but less dominant than IIT or GWT",
        evidence: ["Hundreds of citations", "Influences philosophy of mind", "Growing empirical research"],
        citations: ["Google Scholar"],
        explanation:
          "HOT is influential in philosophy of mind and consciousness research, though less dominant than IIT or GWT. It provides a clear framework for understanding consciousness.",
      },
    },
    testablePredictions: [
      "Meta-representation should correlate with consciousness",
      "Anesthetics should impair meta-representation",
      "Only creatures with higher-order thoughts should be conscious",
      "Brain lesions should impair meta-representation",
      "Consciousness should require prefrontal activation",
    ],
    majorCriticisms: [
      "Infinite regress problem: higher-order thoughts need higher-order thoughts",
      "Difficult to test empirically",
      "May not explain all forms of consciousness",
      "Predicts limited consciousness in animals",
      "Doesn't explain why meta-representation generates consciousness",
    ],
    scientificInfluence: "High",
    relatedConcepts: ["Consciousness", "Meta-representation", "Self-awareness", "Thought"],
    relatedDebates: ["Hard Problem", "Animal Consciousness"],
    keyBooks: ["conscious-mind", "consciousness-explained"],
  },

  pp: {
    id: "pp",
    name: "Predictive Processing",
    researchers: ["Andy Clark", "Anil Seth", "Jakob Hohwy"],
    year: 2013,
    color: "from-indigo-500 to-blue-600",
    shortDescription: "Consciousness emerges from the brain's prediction of sensory input",
    fullDescription:
      "Predictive Processing proposes that the brain is fundamentally a prediction machine. Consciousness emerges from the brain's predictions about sensory input and its own states. Perception is inference, not passive reception.",
    dimensions: {
      definition: {
        position: "Consciousness = predictive model of sensory input and body state",
        evidence: ["Explains perception", "Explains hallucinations"],
        citations: ["Clark 2013", "Seth 2015"],
        explanation:
          "Consciousness arises from the brain's predictions about the world and its own state. The brain generates predictions and updates them based on prediction errors.",
      },
      qualia: {
        position: "Qualia are properties of predictive models",
        evidence: ["Explains why experiences feel the way they do", "Predicts quale structure"],
        citations: ["Seth 2015"],
        explanation:
          "The specific quality of an experience depends on the brain's predictive model. Different predictions generate different qualia.",
      },
      hardProblem: {
        position: "Hard problem is addressed by understanding prediction as embodied inference",
        evidence: ["Explains why prediction feels like something", "Explains subjective experience"],
        citations: ["Seth 2015"],
        explanation:
          "The hard problem is solved by recognizing that consciousness is the brain's embodied prediction of sensory input. Subjective experience arises from the prediction process.",
      },
      self: {
        position: "Self is a predictive model of the body and its states",
        evidence: ["Explains self-awareness", "Predicts self-consciousness in predictive systems"],
        citations: ["Seth 2015"],
        explanation:
          "The sense of self arises from the brain's predictive model of the body. Self-awareness is prediction of bodily and mental states.",
      },
      freeWill: {
        position: "Free will emerges from predictive control of action",
        evidence: ["Explains why choices feel free", "Predicts freedom in predictive systems"],
        citations: ["Clark 2013"],
        explanation:
          "Free will arises from the brain's predictive control of action. Conscious choices are predictions about future actions.",
      },
      bodyRole: {
        position: "Body is central to consciousness through prediction",
        evidence: ["Explains embodied cognition", "Predicts consciousness depends on body"],
        citations: ["Seth 2015"],
        explanation:
          "The body is essential to consciousness because the brain predicts bodily states. Consciousness is fundamentally embodied prediction.",
      },
      emotionRole: {
        position: "Emotion is prediction of body state",
        evidence: ["Explains emotional consciousness", "Predicts emotion in predictive systems"],
        citations: ["Seth 2015"],
        explanation:
          "Emotions are predictions about bodily states. Emotional consciousness is the brain's prediction of emotional body states.",
      },
      neuralBasis: {
        position: "Hierarchical prediction in cortex generates consciousness",
        evidence: ["fMRI shows predictive coding", "Lesions impair prediction"],
        citations: ["Friston 2010", "Seth 2015"],
        explanation:
          "Consciousness arises from hierarchical predictive coding in cortex. Different levels of prediction generate different levels of consciousness.",
      },
      animalConsciousness: {
        position: "Animals with predictive models are conscious",
        evidence: ["Predicts consciousness in many animals", "Explains varying levels of consciousness"],
        citations: ["Clark 2013"],
        explanation:
          "Animals with brains that generate predictive models are conscious. The degree of consciousness depends on prediction sophistication.",
      },
      aiConsciousness: {
        position: "AI can be conscious if it generates embodied predictions",
        evidence: ["Prediction is computational", "Consciousness is substrate-independent"],
        citations: ["Seth 2015"],
        explanation:
          "Consciousness is not biological. Any artificial system that generates embodied predictions would be conscious. Current AI systems lack embodied grounding.",
      },
      evidence: {
        position: "Predictive coding correlates with consciousness",
        evidence: [
          "fMRI shows predictive coding during consciousness",
          "Prediction errors correlate with consciousness",
          "Anesthesia impairs prediction",
          "Sleep reduces prediction",
        ],
        citations: ["Friston 2010", "Seth 2015"],
        explanation:
          "Empirical evidence shows consciousness correlates with predictive coding. When the brain generates predictions, consciousness arises.",
      },
      criticisms: {
        position: "Predictive Processing faces challenges with scope and specificity",
        evidence: [
          "Doesn't explain why prediction generates consciousness",
          "May not explain all forms of consciousness",
          "Difficult to distinguish from other theories",
          "Prediction is ubiquitous but consciousness is not",
        ],
        citations: ["Block 2005", "Dennett 2005"],
        explanation:
          "Critics argue Predictive Processing doesn't explain why prediction generates consciousness. Also, prediction occurs throughout the brain but only some predictions are conscious.",
      },
      predictions: {
        position: "Predictive Processing makes specific predictions",
        evidence: [
          "Predicts consciousness correlates with prediction",
          "Predicts consciousness loss during anesthesia",
          "Predicts embodied consciousness",
          "Predicts consciousness in predictive systems",
        ],
        citations: ["Seth 2015"],
        explanation:
          "Predictive Processing predicts consciousness should correlate with prediction, anesthetics should impair prediction, and consciousness should depend on embodiment.",
      },
      influence: {
        position: "Very High - Predictive Processing is increasingly influential",
        evidence: ["Thousands of citations", "Drives research on neural mechanisms", "Widely adopted in neuroscience"],
        citations: ["Google Scholar"],
        explanation:
          "Predictive Processing has become increasingly influential in neuroscience and consciousness research. It provides a unified framework for understanding perception, cognition, and consciousness.",
      },
    },
    testablePredictions: [
      "Predictive coding should correlate with consciousness",
      "Anesthetics should impair predictive coding",
      "Consciousness should depend on embodied prediction",
      "Brain lesions should impair prediction",
      "Consciousness should require hierarchical prediction",
    ],
    majorCriticisms: [
      "Doesn't explain why prediction generates consciousness",
      "May not explain all forms of consciousness",
      "Prediction is ubiquitous but consciousness is not",
      "Difficult to distinguish from other theories",
      "Embodiment requirement may be too strong",
    ],
    scientificInfluence: "Very High",
    relatedConcepts: ["Consciousness", "Prediction", "Embodiment", "Perception"],
    relatedDebates: ["Hard Problem", "Embodied Cognition"],
    keyBooks: ["being-you", "surfing-uncertainty"],
  },

  ai: {
    id: "ai",
    name: "Active Inference",
    researchers: ["Karl Friston", "Andy Clark"],
    year: 2010,
    color: "from-green-500 to-teal-600",
    shortDescription: "Consciousness arises from active inference and minimizing free energy",
    fullDescription:
      "Active Inference extends Predictive Processing by proposing that consciousness arises from the brain's active minimization of free energy. The brain doesn't just predict; it acts to make its predictions true.",
    dimensions: {
      definition: {
        position: "Consciousness = active minimization of free energy through inference",
        evidence: ["Explains action and perception", "Explains adaptive behavior"],
        citations: ["Friston 2010", "Clark 2013"],
        explanation:
          "Consciousness arises from the brain's active minimization of free energy. The brain generates predictions and acts to confirm them, creating a unified model of self and world.",
      },
      qualia: {
        position: "Qualia are properties of active inference models",
        evidence: ["Explains why experiences feel the way they do", "Predicts quale structure"],
        citations: ["Friston 2010"],
        explanation:
          "The specific quality of an experience depends on the brain's active inference model. Different inference processes generate different qualia.",
      },
      hardProblem: {
        position: "Hard problem is addressed by understanding consciousness as active inference",
        evidence: ["Explains why inference feels like something", "Explains subjective experience"],
        citations: ["Friston 2010"],
        explanation:
          "The hard problem is solved by recognizing that consciousness is the brain's active inference about its own state and the world. Subjective experience arises from active inference.",
      },
      self: {
        position: "Self is an active inference model of the body and its states",
        evidence: ["Explains self-awareness", "Predicts self-consciousness in inferring systems"],
        citations: ["Friston 2010"],
        explanation:
          "The sense of self arises from the brain's active inference about its own state. Self-awareness is active inference of bodily and mental states.",
      },
      freeWill: {
        position: "Free will emerges from active inference and action selection",
        evidence: ["Explains why choices feel free", "Predicts freedom in inferring systems"],
        citations: ["Friston 2010"],
        explanation:
          "Free will arises from the brain's active inference about future actions. Conscious choices are active inferences about what to do.",
      },
      bodyRole: {
        position: "Body is central to consciousness through active inference",
        evidence: ["Explains embodied cognition", "Predicts consciousness depends on body"],
        citations: ["Friston 2010"],
        explanation:
          "The body is essential to consciousness because the brain actively infers and controls bodily states. Consciousness is fundamentally embodied active inference.",
      },
      emotionRole: {
        position: "Emotion is active inference of body state",
        evidence: ["Explains emotional consciousness", "Predicts emotion in inferring systems"],
        citations: ["Friston 2010"],
        explanation:
          "Emotions are active inferences about bodily states. Emotional consciousness is the brain's active inference of emotional body states.",
      },
      neuralBasis: {
        position: "Hierarchical active inference in cortex generates consciousness",
        evidence: ["fMRI shows active inference", "Lesions impair inference"],
        citations: ["Friston 2010"],
        explanation:
          "Consciousness arises from hierarchical active inference in cortex. Different levels of inference generate different levels of consciousness.",
      },
      animalConsciousness: {
        position: "Animals with active inference are conscious",
        evidence: ["Predicts consciousness in many animals", "Explains varying levels of consciousness"],
        citations: ["Friston 2010"],
        explanation:
          "Animals with brains that perform active inference are conscious. The degree of consciousness depends on inference sophistication.",
      },
      aiConsciousness: {
        position: "AI can be conscious if it performs embodied active inference",
        evidence: ["Active inference is computational", "Consciousness is substrate-independent"],
        citations: ["Friston 2010"],
        explanation:
          "Consciousness is not biological. Any artificial system that performs embodied active inference would be conscious. Current AI systems lack embodied grounding.",
      },
      evidence: {
        position: "Active inference correlates with consciousness",
        evidence: [
          "fMRI shows active inference during consciousness",
          "Action correlates with consciousness",
          "Anesthesia impairs active inference",
          "Sleep reduces active inference",
        ],
        citations: ["Friston 2010"],
        explanation:
          "Empirical evidence shows consciousness correlates with active inference. When the brain actively infers and acts, consciousness arises.",
      },
      criticisms: {
        position: "Active Inference faces challenges with scope and empirical testing",
        evidence: [
          "Doesn't explain why active inference generates consciousness",
          "May not explain all forms of consciousness",
          "Difficult to test empirically",
          "Free energy principle is controversial",
        ],
        citations: ["Block 2005", "Dennett 2005"],
        explanation:
          "Critics argue Active Inference doesn't explain why active inference generates consciousness. Also, the free energy principle is controversial and difficult to test.",
      },
      predictions: {
        position: "Active Inference makes specific predictions",
        evidence: [
          "Predicts consciousness correlates with active inference",
          "Predicts consciousness loss during anesthesia",
          "Predicts embodied consciousness",
          "Predicts consciousness in inferring systems",
        ],
        citations: ["Friston 2010"],
        explanation:
          "Active Inference predicts consciousness should correlate with active inference, anesthetics should impair inference, and consciousness should depend on embodiment.",
      },
      influence: {
        position: "High and Growing - Active Inference is increasingly influential",
        evidence: ["Growing citations", "Drives research on neural mechanisms", "Gaining adoption in neuroscience"],
        citations: ["Google Scholar"],
        explanation:
          "Active Inference is increasingly influential in neuroscience and consciousness research. It provides a unified framework for understanding perception, action, and consciousness.",
      },
    },
    testablePredictions: [
      "Active inference should correlate with consciousness",
      "Anesthetics should impair active inference",
      "Consciousness should depend on embodied action",
      "Brain lesions should impair inference",
      "Consciousness should require hierarchical active inference",
    ],
    majorCriticisms: [
      "Doesn't explain why active inference generates consciousness",
      "May not explain all forms of consciousness",
      "Difficult to test empirically",
      "Free energy principle is controversial",
      "Embodiment and action requirements may be too strong",
    ],
    scientificInfluence: "High",
    relatedConcepts: ["Consciousness", "Active Inference", "Free Energy", "Embodiment"],
    relatedDebates: ["Hard Problem", "Embodied Cognition"],
    keyBooks: ["surfing-uncertainty", "predictive-mind"],
  },

  smpt: {
    id: "smpt",
    name: "Self Model Theory of Subjectivity",
    researchers: ["Thomas Metzinger"],
    year: 2003,
    color: "from-pink-500 to-red-600",
    shortDescription: "Consciousness is the brain's self-model becoming transparent",
    fullDescription:
      "SMPT proposes that consciousness is the brain's self-model. The self is a model, not a real entity. Consciousness occurs when the self-model becomes transparent—we mistake the model for reality.",
    dimensions: {
      definition: {
        position: "Consciousness = transparent self-model of the brain",
        evidence: ["Explains self-awareness", "Explains why self feels real"],
        citations: ["Metzinger 2003", "Metzinger 2009"],
        explanation:
          "Consciousness is the brain's self-model becoming transparent. We experience the self-model as the real self, but it's actually a model. Consciousness is this transparent model.",
      },
      qualia: {
        position: "Qualia are properties of the transparent self-model",
        evidence: ["Explains why experiences feel subjective", "Predicts quale structure"],
        citations: ["Metzinger 2003"],
        explanation:
          "The specific quality of an experience depends on the self-model. Different self-models generate different qualia. Qualia are properties of the transparent model.",
      },
      hardProblem: {
        position: "Hard problem is solved by understanding self-model transparency",
        evidence: ["Explains why consciousness feels subjective", "Explains subjective experience"],
        citations: ["Metzinger 2003"],
        explanation:
          "The hard problem is solved by recognizing that consciousness is the transparency of the self-model. Subjective experience arises from the model becoming transparent.",
      },
      self: {
        position: "Self is an illusion—a model the brain creates",
        evidence: ["Explains self-awareness", "Predicts self-consciousness in modeling systems"],
        citations: ["Metzinger 2003", "Metzinger 2009"],
        explanation:
          "The self is not a real entity but a model the brain creates. Self-awareness is the transparency of this model. The self is an illusion.",
      },
      freeWill: {
        position: "Free will is an illusion created by the self-model",
        evidence: ["Explains why choices feel free", "Predicts freedom is illusory"],
        citations: ["Metzinger 2003"],
        explanation:
          "Free will is an illusion created by the self-model. The model makes it seem like we freely choose, but choices are determined by brain processes.",
      },
      bodyRole: {
        position: "Body is represented in the self-model",
        evidence: ["Explains bodily awareness", "Predicts body consciousness"],
        citations: ["Metzinger 2003"],
        explanation:
          "Body awareness is part of the self-model. The body itself is not essential; what matters is how the brain models it.",
      },
      emotionRole: {
        position: "Emotion is part of the self-model",
        evidence: ["Explains emotional consciousness", "Predicts emotion in modeling systems"],
        citations: ["Metzinger 2003"],
        explanation:
          "Emotional consciousness is part of the transparent self-model. Emotions are represented in the self-model.",
      },
      neuralBasis: {
        position: "Cortical midline structures generate the self-model",
        evidence: ["fMRI shows midline activation during self-awareness", "Lesions impair self-awareness"],
        citations: ["Metzinger 2003"],
        explanation:
          "The self-model is generated by cortical midline structures. Consciousness depends on these structures. Damage here impairs self-awareness.",
      },
      animalConsciousness: {
        position: "Animals with self-models are conscious",
        evidence: ["Predicts consciousness in animals with self-models", "Explains varying levels of consciousness"],
        citations: ["Metzinger 2003"],
        explanation:
          "Animals with brains that generate self-models are conscious. The degree of consciousness depends on self-model sophistication.",
      },
      aiConsciousness: {
        position: "AI can be conscious if it generates a transparent self-model",
        evidence: ["Self-modeling is computational", "Consciousness is substrate-independent"],
        citations: ["Metzinger 2003"],
        explanation:
          "Consciousness is not biological. Any artificial system that generates a transparent self-model would be conscious. Current AI systems lack self-models.",
      },
      evidence: {
        position: "Self-model transparency correlates with consciousness",
        evidence: [
          "fMRI shows midline activation during consciousness",
          "Self-awareness correlates with consciousness",
          "Anesthesia impairs self-model",
          "Sleep reduces self-model transparency",
        ],
        citations: ["Metzinger 2003"],
        explanation:
          "Empirical evidence shows consciousness correlates with self-model transparency. When the self-model becomes transparent, consciousness arises.",
      },
      criticisms: {
        position: "SMPT faces challenges with empirical testing and scope",
        evidence: [
          "Difficult to test self-model transparency empirically",
          "May not explain all forms of consciousness",
          "Self-model concept may be too vague",
          "Doesn't explain why self-model generates consciousness",
        ],
        citations: ["Block 2005", "Dennett 2005"],
        explanation:
          "Critics argue SMPT is difficult to test empirically and may not explain all forms of consciousness. The self-model concept is also somewhat vague.",
      },
      predictions: {
        position: "SMPT makes specific predictions",
        evidence: [
          "Predicts consciousness correlates with self-model",
          "Predicts consciousness loss during anesthesia",
          "Predicts self-awareness in modeling systems",
          "Predicts consciousness in systems with self-models",
        ],
        citations: ["Metzinger 2003"],
        explanation:
          "SMPT predicts consciousness should correlate with self-model transparency, anesthetics should impair self-model, and consciousness should depend on self-modeling.",
      },
      influence: {
        position: "Moderate - SMPT is influential in philosophy but less in neuroscience",
        evidence: ["Hundreds of citations", "Influences philosophy of mind", "Growing neuroscience research"],
        citations: ["Google Scholar"],
        explanation:
          "SMPT is influential in philosophy of mind and consciousness research, though less dominant in neuroscience. It provides a clear framework for understanding the self.",
      },
    },
    testablePredictions: [
      "Self-model transparency should correlate with consciousness",
      "Anesthetics should impair self-model",
      "Self-awareness should correlate with consciousness",
      "Brain lesions should impair self-model",
      "Consciousness should require cortical midline activation",
    ],
    majorCriticisms: [
      "Difficult to test self-model transparency empirically",
      "May not explain all forms of consciousness",
      "Self-model concept may be too vague",
      "Doesn't explain why self-model generates consciousness",
      "May overstate the illusory nature of the self",
    ],
    scientificInfluence: "Moderate",
    relatedConcepts: ["Consciousness", "Self", "Self-Model", "Illusion"],
    relatedDebates: ["Hard Problem", "Is the Self Real or Illusory"],
    keyBooks: ["ego-tunnel", "consciousness-explained"],
  },

  ac: {
    id: "ac",
    name: "Affective Consciousness Theory",
    researchers: ["Mark Solms", "Jaak Panksepp"],
    year: 2018,
    color: "from-red-500 to-pink-600",
    shortDescription: "Consciousness arises from the brain's affective (emotional) systems",
    fullDescription:
      "Affective Consciousness proposes that consciousness originates in the brain's affective systems, not cognitive ones. Feelings are primary to consciousness. Consciousness is fundamentally emotional.",
    dimensions: {
      definition: {
        position: "Consciousness = affective experience arising from emotional systems",
        evidence: ["Explains emotional consciousness", "Explains why consciousness feels subjective"],
        citations: ["Solms 2021", "Panksepp 2005"],
        explanation:
          "Consciousness arises from the brain's affective systems. Feelings, not thoughts, are primary. Consciousness is fundamentally emotional and subjective.",
      },
      qualia: {
        position: "Qualia are properties of affective states",
        evidence: ["Explains why experiences feel the way they do", "Predicts quale structure"],
        citations: ["Solms 2021"],
        explanation:
          "The specific quality of an experience depends on affective states. Different emotional states generate different qualia. Qualia are emotional properties.",
      },
      hardProblem: {
        position: "Hard problem is solved by understanding consciousness as affective",
        evidence: ["Explains why consciousness feels subjective", "Explains subjective experience"],
        citations: ["Solms 2021"],
        explanation:
          "The hard problem is solved by recognizing that consciousness is fundamentally affective. Subjective experience arises from emotional systems.",
      },
      self: {
        position: "Self arises from affective experience of the body",
        evidence: ["Explains self-awareness", "Predicts self-consciousness in feeling creatures"],
        citations: ["Solms 2021"],
        explanation:
          "The sense of self arises from affective experience of bodily states. Self-awareness is emotional awareness of the body and mind.",
      },
      freeWill: {
        position: "Free will emerges from affective motivation and choice",
        evidence: ["Explains why choices feel free", "Predicts freedom in feeling creatures"],
        citations: ["Solms 2021"],
        explanation:
          "Free will arises from affective motivation. Conscious choices are emotionally motivated. Freedom emerges from emotional agency.",
      },
      bodyRole: {
        position: "Body is central to consciousness through affective systems",
        evidence: ["Explains embodied emotion", "Predicts consciousness depends on body"],
        citations: ["Solms 2021"],
        explanation:
          "The body is essential to consciousness because affective systems depend on bodily states. Consciousness is fundamentally embodied emotion.",
      },
      emotionRole: {
        position: "Emotion is the foundation of consciousness",
        evidence: ["Explains emotional consciousness", "Predicts emotion is primary"],
        citations: ["Solms 2021"],
        explanation:
          "Emotion is not just part of consciousness; it is the foundation. Consciousness arises from emotional systems. Feelings are primary.",
      },
      neuralBasis: {
        position: "Brainstem and limbic systems generate consciousness",
        evidence: ["fMRI shows limbic activation during consciousness", "Brainstem damage impairs consciousness"],
        citations: ["Solms 2021"],
        explanation:
          "Consciousness arises from brainstem and limbic systems. These emotional systems are the neural basis of consciousness, not cortex.",
      },
      animalConsciousness: {
        position: "Animals with affective systems are conscious",
        evidence: ["Predicts consciousness in many animals", "Explains varying levels of consciousness"],
        citations: ["Solms 2021"],
        explanation:
          "Animals with brains that generate affective states are conscious. The degree of consciousness depends on affective system sophistication.",
      },
      aiConsciousness: {
        position: "AI can be conscious if it generates affective states",
        evidence: ["Affective systems are computational", "Consciousness is substrate-independent"],
        citations: ["Solms 2021"],
        explanation:
          "Consciousness is not biological. Any artificial system that generates affective states would be conscious. Current AI systems lack affective systems.",
      },
      evidence: {
        position: "Affective system activation correlates with consciousness",
        evidence: [
          "fMRI shows limbic activation during consciousness",
          "Emotion correlates with consciousness",
          "Anesthesia impairs affective systems",
          "Sleep reduces affective consciousness",
        ],
        citations: ["Solms 2021"],
        explanation:
          "Empirical evidence shows consciousness correlates with affective system activation. When emotional systems are active, consciousness arises.",
      },
      criticisms: {
        position: "Affective Consciousness faces challenges with scope and mechanism",
        evidence: [
          "Doesn't explain cognitive consciousness",
          "May overstate emotion's role",
          "Difficult to distinguish from other theories",
          "Doesn't explain why affective systems generate consciousness",
        ],
        citations: ["Block 2005", "Dennett 2005"],
        explanation:
          "Critics argue Affective Consciousness may overstate emotion's role and doesn't explain cognitive forms of consciousness. Also difficult to distinguish from other theories.",
      },
      predictions: {
        position: "Affective Consciousness makes specific predictions",
        evidence: [
          "Predicts consciousness correlates with affective activation",
          "Predicts consciousness loss during anesthesia",
          "Predicts emotion is fundamental to consciousness",
          "Predicts consciousness in affective systems",
        ],
        citations: ["Solms 2021"],
        explanation:
          "Affective Consciousness predicts consciousness should correlate with affective activation, anesthetics should impair affective systems, and emotion should be fundamental.",
      },
      influence: {
        position: "Growing - Affective Consciousness is increasingly influential",
        evidence: ["Growing citations", "Drives research on emotion and consciousness", "Gaining adoption in neuroscience"],
        citations: ["Google Scholar"],
        explanation:
          "Affective Consciousness is increasingly influential in neuroscience and consciousness research. It challenges the dominance of cognitive theories.",
      },
    },
    testablePredictions: [
      "Affective system activation should correlate with consciousness",
      "Anesthetics should impair affective systems",
      "Emotion should be fundamental to consciousness",
      "Brain lesions should impair affective consciousness",
      "Consciousness should require brainstem and limbic activation",
    ],
    majorCriticisms: [
      "Doesn't explain cognitive consciousness",
      "May overstate emotion's role",
      "Difficult to distinguish from other theories",
      "Doesn't explain why affective systems generate consciousness",
      "May underestimate cognitive contributions to consciousness",
    ],
    scientificInfluence: "Growing",
    relatedConcepts: ["Consciousness", "Emotion", "Affect", "Feeling"],
    relatedDebates: ["Hard Problem", "Role of Emotion"],
    keyBooks: ["hidden-spring", "self-comes-mind"],
  },

  np: {
    id: "np",
    name: "Neurophenomenology",
    researchers: ["Francisco Varela", "Evan Thompson"],
    year: 1991,
    color: "from-teal-500 to-cyan-600",
    shortDescription: "Consciousness requires integrating neuroscience and phenomenology",
    fullDescription:
      "Neurophenomenology proposes that consciousness can only be understood by integrating neuroscience and phenomenology. First-person experience and third-person science must inform each other.",
    dimensions: {
      definition: {
        position: "Consciousness = lived experience studied through neuroscience and phenomenology",
        evidence: ["Explains subjective experience", "Explains why science alone is insufficient"],
        citations: ["Varela 1991", "Thompson 2007"],
        explanation:
          "Consciousness is lived experience. Understanding it requires both neuroscience (third-person) and phenomenology (first-person). Neither alone is sufficient.",
      },
      qualia: {
        position: "Qualia are properties of lived experience studied phenomenologically",
        evidence: ["Explains why experiences feel the way they do", "Predicts quale structure"],
        citations: ["Varela 1991"],
        explanation:
          "Qualia are the subjective properties of experience. Understanding them requires phenomenological investigation of lived experience.",
      },
      hardProblem: {
        position: "Hard problem is addressed by integrating phenomenology and neuroscience",
        evidence: ["Explains why consciousness is subjective", "Explains subjective experience"],
        citations: ["Varela 1991"],
        explanation:
          "The hard problem is solved by recognizing that consciousness requires both first-person and third-person investigation. Phenomenology and neuroscience must inform each other.",
      },
      self: {
        position: "Self is lived experience of embodied existence",
        evidence: ["Explains self-awareness", "Predicts self-consciousness in living creatures"],
        citations: ["Thompson 2007"],
        explanation:
          "The sense of self arises from lived experience of embodied existence. Self-awareness is phenomenological awareness of being a living body.",
      },
      freeWill: {
        position: "Free will emerges from lived experience of agency",
        evidence: ["Explains why choices feel free", "Predicts freedom in living creatures"],
        citations: ["Varela 1991"],
        explanation:
          "Free will arises from lived experience of agency. Conscious choices are experienced as free. Freedom is a phenomenological property of lived experience.",
      },
      bodyRole: {
        position: "Body is central to consciousness through lived embodiment",
        evidence: ["Explains embodied cognition", "Predicts consciousness depends on body"],
        citations: ["Thompson 2007"],
        explanation:
          "The body is essential to consciousness because consciousness is lived embodied existence. Consciousness is fundamentally embodied.",
      },
      emotionRole: {
        position: "Emotion is part of lived embodied experience",
        evidence: ["Explains emotional consciousness", "Predicts emotion in living creatures"],
        citations: ["Varela 1991"],
        explanation:
          "Emotional consciousness is part of lived embodied experience. Emotions are lived experiences of the body.",
      },
      neuralBasis: {
        position: "Neural basis is studied through neurophenomenological investigation",
        evidence: ["fMRI correlates with phenomenological reports", "Lesions correlate with phenomenological changes"],
        citations: ["Varela 1991"],
        explanation:
          "The neural basis of consciousness is discovered by correlating neuroscience with phenomenological investigation. Neither alone is sufficient.",
      },
      animalConsciousness: {
        position: "Animals with lived embodied experience are conscious",
        evidence: ["Predicts consciousness in many animals", "Explains varying levels of consciousness"],
        citations: ["Thompson 2007"],
        explanation:
          "Animals with lived embodied experience are conscious. The degree of consciousness depends on embodied experience sophistication.",
      },
      aiConsciousness: {
        position: "AI can be conscious if it has lived embodied experience",
        evidence: ["Embodied experience is computational", "Consciousness is substrate-independent"],
        citations: ["Thompson 2007"],
        explanation:
          "Consciousness is not biological. Any artificial system with lived embodied experience would be conscious. Current AI systems lack embodied experience.",
      },
      evidence: {
        position: "Evidence comes from correlating neuroscience and phenomenology",
        evidence: [
          "Phenomenological reports correlate with neural activity",
          "Neural changes correlate with phenomenological changes",
          "Anesthesia correlates with loss of phenomenological experience",
          "Sleep correlates with changes in phenomenological experience",
        ],
        citations: ["Varela 1991"],
        explanation:
          "Evidence for consciousness comes from correlating neuroscience with phenomenological investigation. Both perspectives are necessary.",
      },
      criticisms: {
        position: "Neurophenomenology faces challenges with methodology and scope",
        evidence: [
          "Phenomenology is subjective and difficult to standardize",
          "May not explain all forms of consciousness",
          "Difficult to integrate phenomenology and neuroscience",
          "Doesn't explain why embodied experience generates consciousness",
        ],
        citations: ["Block 2005", "Dennett 2005"],
        explanation:
          "Critics argue phenomenology is subjective and difficult to standardize. Also challenging to integrate phenomenology and neuroscience effectively.",
      },
      predictions: {
        position: "Neurophenomenology makes specific predictions",
        evidence: [
          "Predicts consciousness correlates with embodied experience",
          "Predicts consciousness loss during anesthesia",
          "Predicts phenomenological changes correlate with neural changes",
          "Predicts consciousness in living creatures",
        ],
        citations: ["Varela 1991"],
        explanation:
          "Neurophenomenology predicts consciousness should correlate with embodied experience, anesthetics should impair experience, and phenomenology should correlate with neuroscience.",
      },
      influence: {
        position: "Moderate and Growing - Neurophenomenology is increasingly influential",
        evidence: ["Growing citations", "Drives research on embodied consciousness", "Gaining adoption in neuroscience"],
        citations: ["Google Scholar"],
        explanation:
          "Neurophenomenology is increasingly influential in consciousness research. It challenges the dominance of purely neuroscientific approaches.",
      },
    },
    testablePredictions: [
      "Phenomenological reports should correlate with neural activity",
      "Neural changes should correlate with phenomenological changes",
      "Anesthesia should impair phenomenological experience",
      "Consciousness should require embodied experience",
      "Consciousness should integrate first-person and third-person perspectives",
    ],
    majorCriticisms: [
      "Phenomenology is subjective and difficult to standardize",
      "May not explain all forms of consciousness",
      "Difficult to integrate phenomenology and neuroscience",
      "Doesn't explain why embodied experience generates consciousness",
      "May be too philosophical for empirical science",
    ],
    scientificInfluence: "Moderate",
    relatedConcepts: ["Consciousness", "Phenomenology", "Embodiment", "Experience"],
    relatedDebates: ["Hard Problem", "Embodied Cognition"],
    keyBooks: ["neurophenomenology", "self-comes-mind"],
  },

  ce: {
    id: "ce",
    name: "Constructed Emotion Theory",
    researchers: ["Lisa Feldman Barrett"],
    year: 2017,
    color: "from-orange-500 to-red-600",
    shortDescription: "Consciousness and emotion are constructed by the brain based on past experience",
    fullDescription:
      "Constructed Emotion Theory proposes that emotions are not universal reactions but constructed by the brain based on past experience and context. Consciousness is similarly constructed.",
    dimensions: {
      definition: {
        position: "Consciousness = constructed model of experience based on past learning",
        evidence: ["Explains subjective experience", "Explains cultural variation in consciousness"],
        citations: ["Barrett 2017"],
        explanation:
          "Consciousness is constructed by the brain based on past experience. The brain predicts experience based on learning. Consciousness is not passive perception but active construction.",
      },
      qualia: {
        position: "Qualia are constructed properties of experience",
        evidence: ["Explains why experiences feel the way they do", "Predicts quale variation"],
        citations: ["Barrett 2017"],
        explanation:
          "Qualia are constructed by the brain based on past experience. Different learning histories generate different qualia. Qualia are not intrinsic but constructed.",
      },
      hardProblem: {
        position: "Hard problem is addressed by understanding consciousness as constructed",
        evidence: ["Explains why consciousness feels subjective", "Explains subjective experience"],
        citations: ["Barrett 2017"],
        explanation:
          "The hard problem is solved by recognizing that consciousness is constructed by the brain. Subjective experience arises from the brain's construction process.",
      },
      self: {
        position: "Self is constructed by the brain based on past experience",
        evidence: ["Explains self-awareness", "Predicts self-consciousness in learning creatures"],
        citations: ["Barrett 2017"],
        explanation:
          "The sense of self is constructed by the brain based on past experience. Self-awareness is the brain's constructed model of itself.",
      },
      freeWill: {
        position: "Free will is constructed experience of agency",
        evidence: ["Explains why choices feel free", "Predicts freedom in constructing creatures"],
        citations: ["Barrett 2017"],
        explanation:
          "Free will is the brain's constructed experience of agency. Conscious choices feel free because the brain constructs them that way.",
      },
      bodyRole: {
        position: "Body provides input to construction but is not essential",
        evidence: ["Explains embodied emotion", "Predicts consciousness depends on body"],
        citations: ["Barrett 2017"],
        explanation:
          "The body provides sensory input that the brain uses to construct experience. But consciousness depends on the construction, not the body itself.",
      },
      emotionRole: {
        position: "Emotion is constructed and fundamental to consciousness",
        evidence: ["Explains emotional consciousness", "Predicts emotion is constructed"],
        citations: ["Barrett 2017"],
        explanation:
          "Emotions are constructed by the brain based on past experience. Emotional consciousness is the brain's construction of emotional experience.",
      },
      neuralBasis: {
        position: "Prediction networks throughout cortex construct consciousness",
        evidence: ["fMRI shows predictive networks", "Lesions impair construction"],
        citations: ["Barrett 2017"],
        explanation:
          "Consciousness is constructed by prediction networks throughout cortex. Different networks construct different aspects of experience.",
      },
      animalConsciousness: {
        position: "Animals with learning and construction are conscious",
        evidence: ["Predicts consciousness in many animals", "Explains varying levels of consciousness"],
        citations: ["Barrett 2017"],
        explanation:
          "Animals with brains that construct experience are conscious. The degree of consciousness depends on construction sophistication.",
      },
      aiConsciousness: {
        position: "AI can be conscious if it constructs experience",
        evidence: ["Construction is computational", "Consciousness is substrate-independent"],
        citations: ["Barrett 2017"],
        explanation:
          "Consciousness is not biological. Any artificial system that constructs experience would be conscious. Current AI systems have limited construction.",
      },
      evidence: {
        position: "Construction correlates with consciousness",
        evidence: [
          "fMRI shows predictive networks during consciousness",
          "Learning changes consciousness",
          "Anesthesia impairs construction",
          "Sleep reduces construction",
        ],
        citations: ["Barrett 2017"],
        explanation:
          "Empirical evidence shows consciousness correlates with brain construction. When the brain constructs experience, consciousness arises.",
      },
      criticisms: {
        position: "Constructed Emotion Theory faces challenges with scope and mechanism",
        evidence: [
          "Doesn't explain why construction generates consciousness",
          "May not explain all forms of consciousness",
          "Difficult to distinguish from other theories",
          "May overstate construction's role",
        ],
        citations: ["Block 2005", "Dennett 2005"],
        explanation:
          "Critics argue Constructed Emotion Theory doesn't explain why construction generates consciousness. Also difficult to distinguish from predictive processing.",
      },
      predictions: {
        position: "Constructed Emotion Theory makes specific predictions",
        evidence: [
          "Predicts consciousness correlates with construction",
          "Predicts consciousness loss during anesthesia",
          "Predicts emotional consciousness is constructed",
          "Predicts consciousness in constructing systems",
        ],
        citations: ["Barrett 2017"],
        explanation:
          "Constructed Emotion Theory predicts consciousness should correlate with construction, anesthetics should impair construction, and emotion should be constructed.",
      },
      influence: {
        position: "Growing - Constructed Emotion Theory is increasingly influential",
        evidence: ["Growing citations", "Drives research on emotion and consciousness", "Gaining adoption in psychology"],
        citations: ["Google Scholar"],
        explanation:
          "Constructed Emotion Theory is increasingly influential in psychology and consciousness research. It challenges traditional views of emotion and consciousness.",
      },
    },
    testablePredictions: [
      "Construction should correlate with consciousness",
      "Anesthetics should impair construction",
      "Learning should change consciousness",
      "Brain lesions should impair construction",
      "Consciousness should require predictive construction",
    ],
    majorCriticisms: [
      "Doesn't explain why construction generates consciousness",
      "May not explain all forms of consciousness",
      "Difficult to distinguish from predictive processing",
      "May overstate construction's role",
      "Doesn't explain why emotions feel the way they do",
    ],
    scientificInfluence: "Growing",
    relatedConcepts: ["Consciousness", "Emotion", "Construction", "Prediction"],
    relatedDebates: ["Hard Problem", "Role of Emotion"],
    keyBooks: ["constructed-emotion", "being-you"],
  },

  ec: {
    id: "ec",
    name: "Embodied Cognition",
    researchers: ["Antonio Damasio", "Francisco Varela"],
    year: 1994,
    color: "from-red-500 to-orange-600",
    shortDescription: "Consciousness arises from the dynamic interaction of brain, body, and environment",
    fullDescription:
      "Embodied Cognition proposes that consciousness arises from the dynamic interaction between brain, body, and environment. The body is not peripheral but central to consciousness.",
    dimensions: {
      definition: {
        position: "Consciousness = embodied interaction of brain, body, and environment",
        evidence: ["Explains embodied experience", "Explains why consciousness feels embodied"],
        citations: ["Damasio 1994", "Varela 1991"],
        explanation:
          "Consciousness arises from the dynamic interaction between brain, body, and environment. Consciousness is not in the brain alone but in the whole embodied system.",
      },
      qualia: {
        position: "Qualia are properties of embodied interaction",
        evidence: ["Explains why experiences feel embodied", "Predicts quale structure"],
        citations: ["Damasio 1994"],
        explanation:
          "The specific quality of an experience depends on embodied interaction. Different embodied interactions generate different qualia.",
      },
      hardProblem: {
        position: "Hard problem is addressed by understanding consciousness as embodied",
        evidence: ["Explains why consciousness feels embodied", "Explains subjective experience"],
        citations: ["Damasio 1994"],
        explanation:
          "The hard problem is solved by recognizing that consciousness is fundamentally embodied. Subjective experience arises from embodied interaction.",
      },
      self: {
        position: "Self arises from embodied interaction with environment",
        evidence: ["Explains self-awareness", "Predicts self-consciousness in embodied creatures"],
        citations: ["Damasio 1994"],
        explanation:
          "The sense of self arises from embodied interaction with the environment. Self-awareness is embodied awareness of being in the world.",
      },
      freeWill: {
        position: "Free will emerges from embodied agency",
        evidence: ["Explains why choices feel free", "Predicts freedom in embodied creatures"],
        citations: ["Damasio 1994"],
        explanation:
          "Free will arises from embodied agency. Conscious choices are embodied actions. Freedom emerges from embodied interaction with the world.",
      },
      bodyRole: {
        position: "Body is central to consciousness, not peripheral",
        evidence: ["Explains embodied cognition", "Predicts consciousness depends on body"],
        citations: ["Damasio 1994"],
        explanation:
          "The body is essential to consciousness. Consciousness is not in the brain alone but in the embodied system. Body and brain are inseparable.",
      },
      emotionRole: {
        position: "Emotion is fundamental to consciousness through embodiment",
        evidence: ["Explains emotional consciousness", "Predicts emotion is embodied"],
        citations: ["Damasio 1994"],
        explanation:
          "Emotions are embodied experiences. Emotional consciousness arises from embodied emotional states. Emotion is central to consciousness.",
      },
      neuralBasis: {
        position: "Insula and somatosensory cortex are key to embodied consciousness",
        evidence: ["fMRI shows insula activation during consciousness", "Lesions impair embodied awareness"],
        citations: ["Damasio 1994"],
        explanation:
          "Consciousness arises from brain regions that represent the body. The insula and somatosensory cortex are key. Consciousness depends on bodily representation.",
      },
      animalConsciousness: {
        position: "Animals with embodied interaction are conscious",
        evidence: ["Predicts consciousness in many animals", "Explains varying levels of consciousness"],
        citations: ["Damasio 1994"],
        explanation:
          "Animals with embodied interaction with their environment are conscious. The degree of consciousness depends on embodied interaction sophistication.",
      },
      aiConsciousness: {
        position: "AI can be conscious if it has embodied interaction",
        evidence: ["Embodied interaction is computational", "Consciousness is substrate-independent"],
        citations: ["Damasio 1994"],
        explanation:
          "Consciousness is not biological. Any artificial system with embodied interaction would be conscious. Current AI systems lack embodied interaction.",
      },
      evidence: {
        position: "Embodied interaction correlates with consciousness",
        evidence: [
          "fMRI shows insula activation during consciousness",
          "Bodily awareness correlates with consciousness",
          "Anesthesia impairs embodied awareness",
          "Sleep reduces embodied consciousness",
        ],
        citations: ["Damasio 1994"],
        explanation:
          "Empirical evidence shows consciousness correlates with embodied interaction. When the brain interacts with the body and environment, consciousness arises.",
      },
      criticisms: {
        position: "Embodied Cognition faces challenges with scope and mechanism",
        evidence: [
          "Doesn't explain why embodiment generates consciousness",
          "May not explain all forms of consciousness",
          "Difficult to distinguish from other theories",
          "May overstate embodiment's role",
        ],
        citations: ["Block 2005", "Dennett 2005"],
        explanation:
          "Critics argue Embodied Cognition doesn't explain why embodiment generates consciousness. Also challenging to distinguish from other theories.",
      },
      predictions: {
        position: "Embodied Cognition makes specific predictions",
        evidence: [
          "Predicts consciousness correlates with embodied interaction",
          "Predicts consciousness loss during anesthesia",
          "Predicts embodied consciousness",
          "Predicts consciousness in embodied systems",
        ],
        citations: ["Damasio 1994"],
        explanation:
          "Embodied Cognition predicts consciousness should correlate with embodied interaction, anesthetics should impair embodiment, and consciousness should depend on body.",
      },
      influence: {
        position: "High - Embodied Cognition is influential in consciousness research",
        evidence: ["Thousands of citations", "Drives research on embodied consciousness", "Widely adopted in neuroscience"],
        citations: ["Google Scholar"],
        explanation:
          "Embodied Cognition is highly influential in consciousness research. It challenges the dominance of brain-centric approaches.",
      },
    },
    testablePredictions: [
      "Embodied interaction should correlate with consciousness",
      "Anesthetics should impair embodied awareness",
      "Body damage should impair consciousness",
      "Brain lesions should impair embodied consciousness",
      "Consciousness should require insula and somatosensory activation",
    ],
    majorCriticisms: [
      "Doesn't explain why embodiment generates consciousness",
      "May not explain all forms of consciousness",
      "Difficult to distinguish from other theories",
      "May overstate embodiment's role",
      "Doesn't explain disembodied consciousness",
    ],
    scientificInfluence: "High",
    relatedConcepts: ["Consciousness", "Embodiment", "Body", "Emotion"],
    relatedDebates: ["Hard Problem", "Embodied Cognition"],
    keyBooks: ["descartes-error", "self-comes-mind"],
  },
};
